spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/songshiyu/config-server.git
          #search-paths:
          force-pull: true

server:
  port: 60000